// Code generated by sqlode. DO NOT EDIT.

import sqlode/runtime.{type Value}

pub type GetTaskParams {
  GetTaskParams(id: String)
}

pub fn get_task_values(params: GetTaskParams) -> List(Value) {
  [runtime.string(params.id)]
}

pub type AddTaskParams {
  AddTaskParams(id: String, title: String, state: String)
}

pub fn add_task_values(params: AddTaskParams) -> List(Value) {
  [
    runtime.string(params.id),
    runtime.string(params.title),
    runtime.string(params.state),
  ]
}

pub type RemoveTaskParams {
  RemoveTaskParams(id: String)
}

pub fn remove_task_values(params: RemoveTaskParams) -> List(Value) {
  [runtime.string(params.id)]
}

pub type UpdateTaskStateParams {
  UpdateTaskStateParams(state: String, id: String)
}

pub fn update_task_state_values(params: UpdateTaskStateParams) -> List(Value) {
  [runtime.string(params.state), runtime.string(params.id)]
}
