// Code generated by sqlode. DO NOT EDIT.
// engine: sqlite
// runtime: native

import db/models
import db/params
import gleam/dynamic/decode
import sqlode/runtime

pub fn all() -> List(runtime.QueryInfo) {
  [
    runtime.QueryInfo(
      name: "AllTask",
      sql: "select id, title, state from tasks order by id;",
      command: runtime.Many,
      param_count: 0,
    ),
    runtime.QueryInfo(
      name: "GetTask",
      sql: "select id, title, state from tasks where id = ?1;",
      command: runtime.One,
      param_count: 1,
    ),
    runtime.QueryInfo(
      name: "AddTask",
      sql: "insert into tasks(id, title, state) values(?1, ?2, ?3);",
      command: runtime.Exec,
      param_count: 3,
    ),
    runtime.QueryInfo(
      name: "RemoveTask",
      sql: "delete from tasks where id = ?1;",
      command: runtime.Exec,
      param_count: 1,
    ),
    runtime.QueryInfo(
      name: "UpdateTaskState",
      sql: "update tasks set state = ?1 where id = ?2;",
      command: runtime.Exec,
      param_count: 2,
    ),
  ]
}

pub fn all_task() -> runtime.RawQuery(Nil) {
  runtime.RawQuery(
    name: "AllTask",
    sql: "select id, title, state from tasks order by id;",
    command: runtime.Many,
    param_count: 0,
    placeholder_style: runtime.QuestionNumbered,
    encode: fn(_) { [] },
    slice_info: fn(_) { [] },
  )
}

pub fn get_task() -> runtime.RawQuery(params.GetTaskParams) {
  runtime.RawQuery(
    name: "GetTask",
    sql: "select id, title, state from tasks where id = __sqlode_param_1__;",
    command: runtime.One,
    param_count: 1,
    placeholder_style: runtime.QuestionNumbered,
    encode: params.get_task_values,
    slice_info: fn(_) { [] },
  )
}

pub fn add_task() -> runtime.RawQuery(params.AddTaskParams) {
  runtime.RawQuery(
    name: "AddTask",
    sql: "insert into tasks(id, title, state) values(__sqlode_param_1__, __sqlode_param_2__, __sqlode_param_3__);",
    command: runtime.Exec,
    param_count: 3,
    placeholder_style: runtime.QuestionNumbered,
    encode: params.add_task_values,
    slice_info: fn(_) { [] },
  )
}

pub fn remove_task() -> runtime.RawQuery(params.RemoveTaskParams) {
  runtime.RawQuery(
    name: "RemoveTask",
    sql: "delete from tasks where id = __sqlode_param_1__;",
    command: runtime.Exec,
    param_count: 1,
    placeholder_style: runtime.QuestionNumbered,
    encode: params.remove_task_values,
    slice_info: fn(_) { [] },
  )
}

pub fn update_task_state() -> runtime.RawQuery(params.UpdateTaskStateParams) {
  runtime.RawQuery(
    name: "UpdateTaskState",
    sql: "update tasks set state = __sqlode_param_1__ where id = __sqlode_param_2__;",
    command: runtime.Exec,
    param_count: 2,
    placeholder_style: runtime.QuestionNumbered,
    encode: params.update_task_state_values,
    slice_info: fn(_) { [] },
  )
}

pub fn prepare_all_task() -> #(String, List(runtime.Value)) {
  runtime.prepare(all_task(), Nil)
}

pub fn prepare_get_task(id id: String) -> #(String, List(runtime.Value)) {
  runtime.prepare(get_task(), params.GetTaskParams(id: id))
}

pub fn prepare_add_task(
  id id: String,
  title title: String,
  state state: String,
) -> #(String, List(runtime.Value)) {
  runtime.prepare(
    add_task(),
    params.AddTaskParams(id: id, title: title, state: state),
  )
}

pub fn prepare_remove_task(id id: String) -> #(String, List(runtime.Value)) {
  runtime.prepare(remove_task(), params.RemoveTaskParams(id: id))
}

pub fn prepare_update_task_state(
  state state: String,
  id id: String,
) -> #(String, List(runtime.Value)) {
  runtime.prepare(
    update_task_state(),
    params.UpdateTaskStateParams(state: state, id: id),
  )
}

pub fn all_task_decoder() -> decode.Decoder(models.AllTaskRow) {
  use id <- decode.field(0, decode.string)
  use title <- decode.field(1, decode.string)
  use state <- decode.field(2, decode.string)
  decode.success(models.Task(id:, title:, state:))
}

pub fn get_task_decoder() -> decode.Decoder(models.GetTaskRow) {
  use id <- decode.field(0, decode.string)
  use title <- decode.field(1, decode.string)
  use state <- decode.field(2, decode.string)
  decode.success(models.Task(id:, title:, state:))
}
