// Code generated by sqlode. DO NOT EDIT.

import db/models
import db/params
import db/queries
import gleam/dynamic/decode
import gleam/list
import gleam/option.{type Option, None, Some}
import gleam/result
import sqlight
import sqlode/runtime

fn value_to_sqlight(value: runtime.Value) -> sqlight.Value {
  case value {
    runtime.Null -> sqlight.null()
    runtime.String(v) -> sqlight.text(v)
    runtime.Int(v) -> sqlight.int(v)
    runtime.Float(v) -> sqlight.float(v)
    runtime.Bool(v) -> sqlight.bool(v)
    runtime.Bytes(v) -> sqlight.blob(v)
    runtime.Array(_) ->
      panic as "Array is not supported in the SQLite native adapter. Use raw runtime for array parameters, or ensure sqlode.slice() values are expanded before reaching value_to_sqlight."
  }
}

pub fn all_task(
  db: sqlight.Connection,
) -> Result(List(models.AllTaskRow), sqlight.Error) {
  let q = queries.all_task()
  let #(sql, values) = runtime.prepare(q, Nil)
  sqlight.query(
    sql,
    on: db,
    with: list.map(values, value_to_sqlight),
    expecting: {
      use id <- decode.field(0, decode.string)
      use title <- decode.field(1, decode.string)
      use state <- decode.field(2, decode.string)
      decode.success(models.Task(id:, title:, state:))
    },
  )
}

pub fn get_task(
  db: sqlight.Connection,
  p: params.GetTaskParams,
) -> Result(Option(models.GetTaskRow), sqlight.Error) {
  let q = queries.get_task()
  let #(sql, values) = runtime.prepare(q, p)
  sqlight.query(
    sql,
    on: db,
    with: list.map(values, value_to_sqlight),
    expecting: {
      use id <- decode.field(0, decode.string)
      use title <- decode.field(1, decode.string)
      use state <- decode.field(2, decode.string)
      decode.success(models.Task(id:, title:, state:))
    },
  )
  |> result.map(fn(rows) {
    case rows {
      [row, ..] -> Some(row)
      [] -> None
    }
  })
}

pub fn add_task(
  db: sqlight.Connection,
  p: params.AddTaskParams,
) -> Result(Nil, sqlight.Error) {
  let q = queries.add_task()
  let #(sql, values) = runtime.prepare(q, p)
  sqlight.query(
    sql,
    on: db,
    with: list.map(values, value_to_sqlight),
    expecting: decode.success(Nil),
  )
  |> result.map(fn(_) { Nil })
}

pub fn remove_task(
  db: sqlight.Connection,
  p: params.RemoveTaskParams,
) -> Result(Nil, sqlight.Error) {
  let q = queries.remove_task()
  let #(sql, values) = runtime.prepare(q, p)
  sqlight.query(
    sql,
    on: db,
    with: list.map(values, value_to_sqlight),
    expecting: decode.success(Nil),
  )
  |> result.map(fn(_) { Nil })
}

pub fn update_task_state(
  db: sqlight.Connection,
  p: params.UpdateTaskStateParams,
) -> Result(Nil, sqlight.Error) {
  let q = queries.update_task_state()
  let #(sql, values) = runtime.prepare(q, p)
  sqlight.query(
    sql,
    on: db,
    with: list.map(values, value_to_sqlight),
    expecting: decode.success(Nil),
  )
  |> result.map(fn(_) { Nil })
}
